export interface CountryData {
  countryId: string;
  dualCitizenship: "Yes" | "No" | "Conditional";
  residencyYears: number;
  militaryService: "Yes" | "No" | "De jure" | "Infrequent" | "Choice";
  taxTreaty: "Yes" | "No" | "Several countries";
  votingStatus: "Universal" | "Universal and Compulsory" | "Selective";
  citizenshipByBirth?: "Yes" | "No" | "Conditional";
  citizenshipByDescent?: string;
  citizenshipByMarriage?: string;
  residencyCriteriaBlurb?: string;
  taxationCriteria?: string;
  taxationType?: "Residence-based" | "Territorial" | "No personal income tax" | "Citizenship-based";
}

export const COUNTRY_DATA: Record<string, CountryData> = {
  "Anguilla": {
    "countryId": "AI",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they spent at least 45 days per year on the island for two consecutive years",
    "taxationType": "No personal income tax"
  },
  "Antigua and Barbuda": {
    "countryId": "AG",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals become tax residents after residing in Antigua and Barbuda for at least 183 days in a calendar year",
    "taxationType": "No personal income tax"
  },
  "Argentina": {
    "countryId": "AR",
    "dualCitizenship": "Yes",
    "residencyYears": 2,
    "militaryService": "De jure",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered tax residents if assigned to work in Argentina for more than five years, or if residing in Argentina for more than 12 months (as of the 13th month).",
    "taxationType": "Residence-based"
  },
  "Armenia": {
    "countryId": "AM",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Armenia for at least 183 days within a 12-month period or if their center of vital interests is in Armenia.",
    "taxationType": "Residence-based"
  },
  "Australia": {
    "countryId": "AU",
    "dualCitizenship": "Yes",
    "residencyYears": 4,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "4 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Australia for more than 183 days in a calendar year or have a permanent residence in Australia (unless their permanent home is overseas).",
    "taxationType": "Residence-based"
  },
  "Austria": {
    "countryId": "AT",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "6 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Austria for more than 183 days in a calendar year or have a domicile in Austria.",
    "taxationType": "Residence-based"
  },
  "Bahamas": {
    "countryId": "BS",
    "dualCitizenship": "No",
    "residencyYears": 6,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "7 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in the Bahamas for 183 days or more in a calendar year, permanently or for an indefinite period, or have an expectation to remain in the Bahamas for 183 days or more in a calendar year.",
    "taxationType": "No personal income tax"
  },
  "Belize": {
    "countryId": "BZ",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "De jure",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "1 year",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Belize for at least 183 days in a calendar year or if they have permanent establishment or registered office in Belize.",
    "taxationType": "Territorial"
  },
  "Bermuda": {
    "countryId": "BM",
    "dualCitizenship": "Yes",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "10 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they hold a Permanent Resident's Certificate, or have a Residential Certificate provided they spend at least 60 days annually in Bermuda.",
    "taxationType": "No personal income tax"
  },
  "Brazil": {
    "countryId": "BR",
    "dualCitizenship": "Yes",
    "residencyYears": 4,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they hold a permanent visa and enter Brazil with the intention of residence, or stay in Brazil longer than 183 days in a 12-month period.",
    "taxationType": "Residence-based"
  },
  "Cambodia": {
    "countryId": "KH",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a principal abode in Cambodia, or stay for more than 182 days in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Canada": {
    "countryId": "CA",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they maintain a dwelling place available for their occupation, have their spouse and dependents residing in Canada, or sojourn in Canada for 183 days or more in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Cayman Islands": {
    "countryId": "KY",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in the Cayman Islands for 6 months or more.",
    "taxationType": "No personal income tax"
  },
  "Chile": {
    "countryId": "CL",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Infrequent",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Chile for more than 6 months in a calendar year, or more than 6 months within two consecutive tax years.",
    "taxationType": "Residence-based"
  },
  "Colombia": {
    "countryId": "CO",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Colombia for a continuous or discontinuous period of more than 183 days during any period of 365 consecutive days.",
    "taxationType": "Residence-based"
  },
  "Costa Rica": {
    "countryId": "CR",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have their principal center of vital or economic interests in Costa Rica, or stay in Costa Rica for more than 183 days in a calendar year.",
    "taxationType": "Territorial"
  },
  "Croatia": {
    "countryId": "HR",
    "dualCitizenship": "Yes",
    "residencyYears": 8,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Croatia for more than 183 days or have a permanent residence in Croatia.",
    "taxationType": "Residence-based"
  },
  "Cyprus": {
    "countryId": "CY",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Cyprus for more than 183 days in a calendar year or more than 60 days in the tax year and satisfy other residency conditions.",
    "taxationType": "Residence-based"
  },
  "Czech Republic": {
    "countryId": "CZ",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in the Czech Republic for more than 183 days in a calendar year or have a permanent home available to them in the Czech Republic.",
    "taxationType": "Residence-based"
  },
  "Denmark": {
    "countryId": "DK",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a permanent residence in Denmark, or stay for a consecutive period of at least 6 months (including short stays abroad).",
    "taxationType": "Residence-based"
  },
  "Dominica": {
    "countryId": "DM",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they spent more than 182 days in Dominica in a calendar year or have a permanent home in Dominica.",
    "taxationType": "Residence-based"
  },
  "Dominican Republic": {
    "countryId": "DO",
    "dualCitizenship": "Yes",
    "residencyYears": 2,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in the Dominican Republic for more than 182 days in a calendar year or have their principal center of interests in the Dominican Republic.",
    "taxationType": "Residence-based"
  },
  "Ecuador": {
    "countryId": "EC",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Ecuador for more than 183 days in a calendar year or have their economic interests centered in Ecuador.",
    "taxationType": "Residence-based"
  },
  "Egypt": {
    "countryId": "EG",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Egypt for more than 183 days in a calendar year, or have their primary place of residence in Egypt.",
    "taxationType": "Residence-based"
  },
  "El Salvador": {
    "countryId": "SV",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in El Salvador for more than 200 days in a calendar year.",
    "taxationType": "Territorial"
  },
  "Estonia": {
    "countryId": "EE",
    "dualCitizenship": "Conditional",
    "residencyYears": 8,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Estonia for at least 183 days over the course of a consecutive 12-month period, or their place of residence is registered in the Estonian Population Register.",
    "taxationType": "Residence-based"
  },
  "Finland": {
    "countryId": "FI",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have their permanent home in Finland or stay in Finland for a continuous period of more than six months.",
    "taxationType": "Residence-based"
  },
  "France": {
    "countryId": "FR",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "4 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered tax residents if they have a permanent home in France, if their primary place of residence is in France, or if they perform professional activities in France.",
    "taxationType": "Residence-based"
  },
  "Georgia": {
    "countryId": "GE",
    "dualCitizenship": "No",
    "residencyYears": 10,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stayed in Georgia for more than 183 days in any consecutive 12-month period ending in a tax year.",
    "taxationType": "Residence-based"
  },
  "Germany": {
    "countryId": "DE",
    "dualCitizenship": "Conditional",
    "residencyYears": 8,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they maintain a dwelling in Germany under circumstances that indicate they will keep and use it, or if they stay in Germany for more than six months consecutively or for more than 183 days in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Ghana": {
    "countryId": "GH",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they are present in Ghana for an aggregate period of 183 days or more in any 12-month period that begins or ends during the fiscal year.",
    "taxationType": "Residence-based"
  },
  "Gibraltar": {
    "countryId": "GI",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they spend more than 183 days in a fiscal year in Gibraltar, or have available to them residential accommodation which they occupy at least once in the year.",
    "taxationType": "Territorial"
   },
   "Greece": {
    "countryId": "GR",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they are in Greece for more than 183 days, or have their vital interests (including family ties) in Greece.",
    "taxationType": "Residence-based"
  },
  "Grenada": {
    "countryId": "GD",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Grenada for at least 6 months in a calendar year.",
    "taxationType": "Territorial"
  },
  "Honduras": {
    "countryId": "HN",
    "dualCitizenship": "Conditional",
    "residencyYears": 3,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they remain in Honduras continuously or discontinuously more than 3 months in a calendar year, or if their center of economic interests is in Honduras.",
    "taxationType": "Territorial"
  },
  "Hong Kong": {
    "countryId": "HK",
    "dualCitizenship": "No",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "No",
    "citizenshipByMarriage": "7 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Hong Kong for more than 180 days in a tax year or more than 300 days in two consecutive tax years.",
    "taxationType": "Territorial"
  },
  "Hungary": {
    "countryId": "HU",
    "dualCitizenship": "Yes",
    "residencyYears": 8,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a permanent home or center of vital interests in Hungary, or stay in Hungary for at least 183 days in the calendar year.",
    "taxationType": "Residence-based"
  },
  "Iceland": {
    "countryId": "IS",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Iceland for more than 183 days in a 12-month period, or have their permanent residence in Iceland.",
    "taxationType": "Residence-based"
  },
  "India": {
    "countryId": "IN",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Conditional",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "7 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in India for 182 days or more in a financial year, or 60 days or more in a financial year and 365 days or more in the preceding four financial years.",
    "taxationType": "Residence-based"
  },
  "Indonesia": {
    "countryId": "ID",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Indonesia for more than 183 days within a 12-month period, or reside in Indonesia during a fiscal year with the intention to reside in Indonesia.",
    "taxationType": "Residence-based"
  },
  "Ireland": {
    "countryId": "IE",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they spend 183 days or more in Ireland in a tax year, or 280 days or more in Ireland over a period of two consecutive tax years (with a minimum of 30 days in each year).",
    "taxationType": "Residence-based"
  },
  "Italy": {
    "countryId": "IT",
    "dualCitizenship": "Yes",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they are registered with the Office of Records of the Resident Population in Italy for the greater part of the tax period, or have their habitual abode or center of business and economic interests in Italy for the greater part of the tax period.",
    "taxationType": "Residence-based"
  },
  "Japan": {
    "countryId": "JP",
    "dualCitizenship": "No",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have their domicile in Japan, or have resided in Japan for a continuous period of at least 1 year.",
    "taxationType": "Residence-based"
  },
  "Latvia": {
    "countryId": "LV",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "10 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Latvia for 183 days or more in any 12-month period, or their declared place of residence is in Latvia.",
    "taxationType": "Residence-based"
  },
  "Lithuania": {
    "countryId": "LT",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "10 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Lithuania for 183 days or more in a tax year, or their permanent residence is in Lithuania.",
    "taxationType": "Residence-based"
  },
  "Luxembourg": {
    "countryId": "LU",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they maintain their domicile or center of vital interests in Luxembourg.",
    "taxationType": "Residence-based"
  },
  "Malaysia": {
    "countryId": "MY",
    "dualCitizenship": "No",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Malaysia for 182 days or more in a calendar year.",
    "taxationType": "Territorial"
  },
  "Malta": {
    "countryId": "MT",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Malta for more than 183 days in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Mauritius": {
    "countryId": "MU",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "4 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Mauritius for 183 days or more in a tax year, or if they have been present in Mauritius for an average of at least 270 days in the current tax year and the two preceding tax years.",
    "taxationType": "Residence-based"
  },
  "Mexico": {
    "countryId": "MX",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they establish their home in Mexico, or if their center of vital interests is in Mexico.",
    "taxationType": "Residence-based"
  },
  "Montenegro": {
    "countryId": "ME",
    "dualCitizenship": "Yes",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Montenegro for 183 days or more in a tax year, or have a permanent home or center of vital interests in Montenegro.",
    "taxationType": "Residence-based"
  },
  "Netherlands": {
    "countryId": "NL",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents based on circumstances such as having a permanent home, where the spouse or family lives, and other personal and economic ties to the Netherlands.",
    "taxationType": "Residence-based"
  },
  "New Zealand": {
    "countryId": "NZ",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in New Zealand for more than 183 days in any 12-month period, or have a permanent place of abode in New Zealand.",
    "taxationType": "Residence-based"
  },
  "Norway": {
    "countryId": "NO",
    "dualCitizenship": "Yes",
    "residencyYears": 7,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Norway for more than 183 days in any 12-month period, or more than 270 days in any 36-month period.",
    "taxationType": "Residence-based"
  },
  "Palau": {
    "countryId": "PW",
    "dualCitizenship": "No",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they physically reside in Palau for more than 120 days in a tax year.",
    "taxationType": "Residence-based"
  },
  "Panama": {
    "countryId": "PA",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Panama for more than 183 days in a calendar year, or have established their permanent home in Panama.",
    "taxationType": "Territorial"
  },
  "Paraguay": {
    "countryId": "PY",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Paraguay for more than 120 days in a calendar year.",
    "taxationType": "Territorial"
  },
  "Peru": {
    "countryId": "PE",
    "dualCitizenship": "Yes",
    "residencyYears": 2,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Peru for more than 183 days in any 12-month period.",
    "taxationType": "Residence-based"
  },
  "Philippines": {
    "countryId": "PH",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in the Philippines for an aggregate period of more than 180 days during any calendar year.",
    "taxationType": "Residence-based"
  },
  "Poland": {
    "countryId": "PL",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if their center of vital or economic interests is in Poland or if they stay in Poland for more than 183 days in a tax year.",
    "taxationType": "Residence-based"
  },
  "Portugal": {
    "countryId": "PT",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Portugal for more than 183 days in a calendar year, or have a dwelling in Portugal and use it as their habitual abode, or if the head of the household is a tax resident of Portugal.",
    "taxationType": "Residence-based"
  },
  "Romania": {
    "countryId": "RO",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Romania for 183 days or more in any 12-month period, or have their center of vital interests in Romania, or are Romanian citizens who maintain their domicile in Romania.",
    "taxationType": "Residence-based"
  },
  "San Marino": {
    "countryId": "SM",
    "dualCitizenship": "No",
    "residencyYears": 30,
    "militaryService": "De jure",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "15 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in San Marino for more than 183 days in a calendar year or have their center of interests in San Marino.",
    "taxationType": "Residence-based"
  },
  "Seychelles": {
    "countryId": "SC",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "10 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a permanent home in Seychelles, or remain in Seychelles for more than 183 days in a calendar year.",
    "taxationType": "Territorial"
  },
  "Sierra Leone": {
    "countryId": "SL",
    "dualCitizenship": "No",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Sierra Leone for 182 days or more in a 12-month period or have an intention to establish residence in Sierra Leone.",
    "taxationType": "Residence-based"
  },
  "Singapore": {
    "countryId": "SG",
    "dualCitizenship": "No",
    "residencyYears": 2,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Singapore for 183 days or more in a calendar year, or if they exercise an employment in Singapore for at least 183 days in a calendar year.",
    "taxationType": "Territorial"
  },
  "Slovakia": {
    "countryId": "SK",
    "dualCitizenship": "Conditional",
    "residencyYears": 8,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Slovakia for 183 days or more in a calendar year, or have a permanent residence in Slovakia.",
    "taxationType": "Residence-based"
  },
  "Slovenia": {
    "countryId": "SI",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "10 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a formal residential address in Slovenia, or have their habitual abode or center of personal and economic interests in Slovenia, or are present in Slovenia for more than 183 days in a tax year.",
    "taxationType": "Residence-based"
  },
  "South Africa": {
    "countryId": "ZA",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they are ordinarily resident in South Africa, or meet the physical presence test (more than 91 days in the current tax year, more than 91 days in each of the preceding 5 tax years, and more than 915 days in the preceding 5 tax years).",
    "taxationType": "Residence-based"
  },
  "South Korea": {
    "countryId": "KR",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "2 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a domicile in South Korea for more than 183 days, or plan to reside in South Korea for more than 183 days.",
    "taxationType": "Residence-based"
  },
  "Spain": {
    "countryId": "ES",
    "dualCitizenship": "Conditional",
    "residencyYears": 10,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "1 year",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Spain for more than 183 days in a calendar year, or have their main center of business or economic activities in Spain.",
    "taxationType": "Residence-based"
  },
  "St. Kitts & Nevis": {
    "countryId": "KN",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have permanent residence or stay in St. Kitts and Nevis for at least 183 days in a calendar year.",
    "taxationType": "No personal income tax"
  },
  "St. Lucia": {
    "countryId": "LC",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "No",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in St. Lucia for 183 days or more in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Sweden": {
    "countryId": "SE",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Sweden for 183 days or more in a calendar year, have a permanent home in Sweden, or have essential connections to Sweden (family, business, etc.).",
    "taxationType": "Residence-based"
  },
  "Switzerland": {
    "countryId": "CH",
    "dualCitizenship": "Yes",
    "residencyYears": 10,
    "militaryService": "Choice",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they intend to stay permanently or stay for at least 30 days to be employed, or 90 days without being employed.",
    "taxationType": "Residence-based"
  },
  "Taiwan": {
    "countryId": "TW",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a domicile in Taiwan and habitually reside there, or if they stay in Taiwan for 183 days or more in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Thailand": {
    "countryId": "TH",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Thailand for 180 days or more in a calendar year.",
    "taxationType": "Residence-based"
  },
  "Turkey": {
    "countryId": "TR",
    "dualCitizenship": "Conditional",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Turkey for more than 6 months in a calendar year.",
    "taxationType": "Residence-based"
  },
  "UAE": {
    "countryId": "AE",
    "dualCitizenship": "Conditional",
    "residencyYears": 30,
    "militaryService": "Yes",
    "taxTreaty": "No",
    "votingStatus": "Selective",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "7 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a valid UAE residence visa and intend to make the UAE their primary residence.",
    "taxationType": "No personal income tax"
  },
  "UK": {
    "countryId": "GB",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "No",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they spend 183 days or more in the UK in a tax year, or their only home is in the UK, or they work full-time in the UK.",
    "taxationType": "Residence-based"
  },
  "Uruguay": {
    "countryId": "UY",
    "dualCitizenship": "Yes",
    "residencyYears": 3,
    "militaryService": "De jure",
    "taxTreaty": "Yes",
    "votingStatus": "Universal and Compulsory",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "0 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Uruguay for more than 183 days in a calendar year, have their center of vital interests in Uruguay, or have their economic activities based in Uruguay.",
    "taxationType": "Territorial"
  },
  "USA": {
    "countryId": "US",
    "dualCitizenship": "Yes",
    "residencyYears": 5,
    "militaryService": "De jure",
    "taxTreaty": "Several countries",
    "votingStatus": "Universal",
    "citizenshipByBirth": "Yes",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "3 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they have a green card, or if they meet the substantial presence test (physically present for at least 31 days in the current year and 183 days during a 3-year period).",
    "taxationType": "Citizenship-based"
  },
  "Vietnam": {
    "countryId": "VN",
    "dualCitizenship": "No",
    "residencyYears": 5,
    "militaryService": "Yes",
    "taxTreaty": "Yes",
    "votingStatus": "Universal",
    "citizenshipByBirth": "No",
    "citizenshipByDescent": "Yes",
    "citizenshipByMarriage": "5 years",
    "residencyCriteriaBlurb": "Foreign individuals are considered residents if they stay in Vietnam for 183 days or more in a tax year, or have a registered permanent residence in Vietnam, or have a rented house in Vietnam with a term of 183 days or more in a tax year.",
    "taxationType": "Residence-based"
  }
};
